# Generated by Django 3.2.6 on 2022-01-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uploadDocuments',
            new_name='uploadDocument',
        ),
    ]
