# Generated by Django 3.2.6 on 2022-01-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expapp', '0002_rename_uploaddocuments_uploaddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddocument',
            name='name',
            field=models.CharField(default='pic', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploaddocument',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
    ]
